import type {Metadata} from 'next';
import {Header} from '@/shared/components/shared/header';
import {Container} from "@/shared/components/shared";
import {Suspense} from "react";

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
};

export default async function CartLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense>
        <Header hasCart={false} hasSearch={false} className="border-gray-200"/>
          </Suspense>
        {children}
      </Container>
    </main>
  );
}
